/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view2;

import java.awt.Frame;
import javax.swing.JButton;

/**
 *
 * @author Novak
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundMM1 = new view2.backgroundMM();
        close = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        bNewGame = new javax.swing.JButton();
        bLoadGame = new javax.swing.JButton();
        bCredit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(133, 59));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setUndecorated(true);

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
        });

        bNewGame.setBackground(new java.awt.Color(60, 60, 60));
        bNewGame.setFont(new java.awt.Font("Determination Mono", 0, 14)); // NOI18N
        bNewGame.setForeground(new java.awt.Color(255, 255, 255));
        bNewGame.setText("NEW GAME.....................$0");
        bNewGame.setBorderPainted(false);
        bNewGame.setContentAreaFilled(false);
        bNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bNewGame.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bNewGame.setMaximumSize(new java.awt.Dimension(57, 30));
        bNewGame.setMinimumSize(new java.awt.Dimension(57, 30));
        bNewGame.setPreferredSize(new java.awt.Dimension(57, 30));

        bLoadGame.setBackground(new java.awt.Color(60, 60, 60));
        bLoadGame.setFont(new java.awt.Font("Determination Mono", 0, 14)); // NOI18N
        bLoadGame.setForeground(new java.awt.Color(255, 255, 255));
        bLoadGame.setText("LOAD GAME....................$0");
        bLoadGame.setBorderPainted(false);
        bLoadGame.setContentAreaFilled(false);
        bLoadGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLoadGame.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLoadGame.setMaximumSize(new java.awt.Dimension(57, 30));
        bLoadGame.setMinimumSize(new java.awt.Dimension(57, 30));
        bLoadGame.setPreferredSize(new java.awt.Dimension(57, 30));
        bLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoadGameActionPerformed(evt);
            }
        });

        bCredit.setBackground(new java.awt.Color(60, 60, 60));
        bCredit.setFont(new java.awt.Font("Determination Mono", 0, 14)); // NOI18N
        bCredit.setForeground(new java.awt.Color(255, 255, 255));
        bCredit.setText("CREDIT.......................$0");
        bCredit.setBorderPainted(false);
        bCredit.setContentAreaFilled(false);
        bCredit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCredit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bCredit.setMaximumSize(new java.awt.Dimension(57, 30));
        bCredit.setMinimumSize(new java.awt.Dimension(57, 30));
        bCredit.setPreferredSize(new java.awt.Dimension(57, 30));
        bCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundMM1Layout = new javax.swing.GroupLayout(backgroundMM1);
        backgroundMM1.setLayout(backgroundMM1Layout);
        backgroundMM1Layout.setHorizontalGroup(
            backgroundMM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundMM1Layout.createSequentialGroup()
                .addGroup(backgroundMM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundMM1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mini, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundMM1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addGroup(backgroundMM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 404, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundMM1Layout.setVerticalGroup(
            backgroundMM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundMM1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(backgroundMM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mini, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(bNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundMM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getbCredit() {
        return bCredit;
    }

    public JButton getbLoadGame() {
        return bLoadGame;
    }

    public JButton getbNewGame() {
        return bNewGame;
    }
    
    
    private void bCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCreditActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        this.setState(MainMenu.ICONIFIED);
    }//GEN-LAST:event_miniMouseClicked

    private void bLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoadGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLoadGameActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCredit;
    private javax.swing.JButton bLoadGame;
    private javax.swing.JButton bNewGame;
    private view2.backgroundMM backgroundMM1;
    private javax.swing.JLabel close;
    private javax.swing.JLabel mini;
    // End of variables declaration//GEN-END:variables
}
