/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view2;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Novak
 */
public class NewGame extends javax.swing.JFrame {

    /**
     * Creates new form NewGame
     */
    public NewGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundT1 = new view2.backgroundT();
        bBack = new javax.swing.JButton();
        type = new javax.swing.JComboBox<>();
        diff = new javax.swing.JComboBox<>();
        bPlay = new javax.swing.JButton();
        mini = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(133, 59));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setUndecorated(true);

        bBack.setBackground(new java.awt.Color(60, 60, 60));
        bBack.setFont(new java.awt.Font("Determination Mono", 0, 14)); // NOI18N
        bBack.setForeground(new java.awt.Color(240, 240, 240));
        bBack.setText("BACK.........................$0");
        bBack.setBorderPainted(false);
        bBack.setContentAreaFilled(false);
        bBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bBack.setMaximumSize(new java.awt.Dimension(97, 30));
        bBack.setMinimumSize(new java.awt.Dimension(97, 30));
        bBack.setPreferredSize(new java.awt.Dimension(97, 30));

        type.setBackground(new java.awt.Color(60, 60, 60));
        type.setFont(new java.awt.Font("Determination Mono", 0, 14)); // NOI18N
        type.setForeground(new java.awt.Color(240, 240, 240));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Speed (A)", "Defend (B)", "Attack (C)" }));
        type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        type.setMaximumSize(new java.awt.Dimension(106, 30));
        type.setMinimumSize(new java.awt.Dimension(106, 30));
        type.setPreferredSize(new java.awt.Dimension(106, 30));

        diff.setBackground(new java.awt.Color(60, 60, 60));
        diff.setFont(new java.awt.Font("Determination Mono", 0, 14)); // NOI18N
        diff.setForeground(new java.awt.Color(240, 240, 240));
        diff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal", "Hard" }));
        diff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diff.setMaximumSize(new java.awt.Dimension(106, 30));
        diff.setMinimumSize(new java.awt.Dimension(106, 30));
        diff.setPreferredSize(new java.awt.Dimension(106, 30));

        bPlay.setBackground(new java.awt.Color(60, 60, 60));
        bPlay.setFont(new java.awt.Font("Determination Mono", 0, 14)); // NOI18N
        bPlay.setForeground(new java.awt.Color(240, 240, 240));
        bPlay.setText("NEXT.........................$0");
        bPlay.setBorderPainted(false);
        bPlay.setContentAreaFilled(false);
        bPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPlay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bPlay.setMaximumSize(new java.awt.Dimension(97, 30));
        bPlay.setMinimumSize(new java.awt.Dimension(97, 30));
        bPlay.setPreferredSize(new java.awt.Dimension(97, 30));

        mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
        });

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundT1Layout = new javax.swing.GroupLayout(backgroundT1);
        backgroundT1.setLayout(backgroundT1Layout);
        backgroundT1Layout.setHorizontalGroup(
            backgroundT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundT1Layout.createSequentialGroup()
                .addGroup(backgroundT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundT1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mini, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundT1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(backgroundT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundT1Layout.createSequentialGroup()
                                .addComponent(diff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bBack, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                .addComponent(bPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 644, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundT1Layout.setVerticalGroup(
            backgroundT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundT1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(backgroundT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(mini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addGroup(backgroundT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getbBack() {
        return bBack;
    }

    public JButton getbPlay() {
        return bPlay;
    }

    public JComboBox<String> getComboBoxDif() {
        return diff;
    }

    public JComboBox<String> getComboBoxType() {
        return type;
    }
    
    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        this.setState(NewGame.ICONIFIED);
    }//GEN-LAST:event_miniMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewGame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bPlay;
    private view2.backgroundT backgroundT1;
    private javax.swing.JLabel close;
    private javax.swing.JComboBox<String> diff;
    private javax.swing.JLabel mini;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
